kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: {{ include "team-video.fullname" . }}-prosody
  labels:
    app: {{ include "team-video.fullname" . }}-prosody
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "team-video.fullname" . }}-prosody
  template:
    metadata:
      labels:
        app: {{ include "team-video.fullname" . }}-prosody
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      containers:
       - name: prosody
         ports:
          - containerPort: 5222
          - containerPort: 5280
          - containerPort: 5347
         resources: {}
#         restartPolicy: Always
         lifecycle:
           postStart:
             exec:
               command: ["/bin/bash", "-c", "sleep 60; prosodyctl --config /config/prosody.cfg.lua register {{ .Values.auth.admin.user }} {{ .Values.app.name }}.{{ .Values.app.domain }} {{ .Values.auth.admin.password }}"]
         image: jitsi/prosody
         imagePullPolicy: {{ .Values.app.pullpolicy }}
         env:
          {{ if .Values.auth.enabled}}
          - name: ENABLE_AUTH
            value: "true"
            {{ if .Values.auth.guests}}
          - name: ENABLE_GUESTS
            value: "true"
            {{end}}
          - name: AUTH_TYPE
            value: {{ .Values.auth.type }}
          {{end}}
          - name: XMPP_DOMAIN
            value: {{ .Values.app.name }}.{{ .Values.app.domain }}
            {{ if .Values.auth.guests}}
          - name: XMPP_GUEST_DOMAIN
            value: guest.{{ .Values.app.name }}.{{ .Values.app.domain }}
            {{end}}
          - name: XMPP_AUTH_DOMAIN
            value: auth.{{ .Values.app.name }}.{{ .Values.app.domain }}
          - name: XMPP_MUC_DOMAIN
            value: muc.{{ .Values.app.name }}.{{ .Values.app.domain }}
          - name: JICOFO_COMPONENT_SECRET
            value: {{ .Values.secrets.jicofo.component }}
          - name: JVB_COMPONENT_SECRET
            value: {{ .Values.secrets.jvb.component }}
          - name: JICOFO_AUTH_USER
            value: focus
          - name: JICOFO_AUTH_PASSWORD
            value: {{ .Values.secrets.jicofo.auth }}
          - name: JVB_AUTH_USER
            value: jvb
          - name: JVB_AUTH_PASSWORD
            value: {{ .Values.secrets.jvb.auth }}
          - name: LOG_LEVEL
            value: {{ .Values.logLevel }}
          - name: XMPP_INTERNAL_MUC_DOMAIN
            value: internal-muc.{{ .Values.app.name }}.{{ .Values.app.domain }}
          - name: TZ
            value: Europe/Paris