# Servive for Ingress-Traefik
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
    - protocol: TCP
      name: web
      port: {{ .Values.ports.web }}
      targetPort: {{ .Values.ports.web }}
    - protocol: TCP
      name: websecure
      port: {{ .Values.ports.websecure }}
      targetPort: {{ .Values.ports.websecure }}
  selector:
    app: traefik
  type: LoadBalancer
