# global https redirect
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: global-redirect-http
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-allredirect
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: landingpage
          port: 80
      middlewares:
        - name: global-redirect-http
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: default
spec:
  cipherSuites:
  {{- if .Values.ciphers }}
   {{- range .Values.ciphers }}
   - {{ . }}
   {{- end }}
  {{ else }}
  # a collection of secure cipher suites (tested with sslabs.com)
   - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
   - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
   - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
   - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
   - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
   - "TLS_AES_128_GCM_SHA256"
   - "TLS_AES_256_GCM_SHA384"
   - "TLS_CHACHA20_POLY1305_SHA256"
   - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
   - "TLS_FALLBACK_SCSV"
  {{- end }}