apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "team-share.fullname" . }}-rc-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.limits.data }}
