kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: {{ include "team-chat.name" . }}-rc
  labels:
    app: {{ include "team-chat.name" . }}-rc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "team-chat.name" . }}-rc
  template:
    metadata:
      labels:
        app: {{ include "team-chat.name" . }}-rc
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      volumes:
       - name: rc-uploads-vol
         persistentVolumeClaim:
           claimName: {{ include "team-chat.name" . }}-rc-data
       - name: rc-tmp-vol
         persistentVolumeClaim:
           claimName: {{ include "team-chat.name" . }}-rc-tmp
      restartPolicy: Always
      containers:
       - name: chat
         image: rocketchat/rocket.chat:latest
         imagePullPolicy: Always
         command:
          - bash
          - -c
          - >
            for i in `seq 1 30`; do
              node main.js &&
              s=$$? && break || s=$$?;
              echo \"Tried to connect $$i times. Waiting 5 secs...\";
              sleep 5;
            done; (exit $$s)
         volumeMounts:
           - name: rc-uploads-vol
             mountPath: "/app/uploads"
           - name: rc-tmp-vol
             mountPath: "/tmp"
         ports:
          - name: web
            containerPort: 3000
         env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ROOT_URL
            value: "https://{{ .Values.app.name }}.{{ .Values.app.domain }}"
          - name: PORT
            value: "3000"
          - name: MONGO_URL
            value: 'mongodb://{{ include "team-chat.name" . }}-mongo/rocketchat'
          - name: MONGO_OPLOG_URL
            value: 'mongodb://{{ include "team-chat.name" . }}-mongo.default.svc.cluster.local:27017/local'
          - name: ADMIN_USERNAME
            value: {{ .Values.admin.name }}
          - name: ADMIN_PASS
            value: {{ .Values.admin.password }}
          - name: ADMIN_EMAIL
            value: {{ .Values.admin.mail }}