kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: teamcloud-jicofo
  labels:
    app: teamcloud-jicofo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcloud-jicofo
  template:
    metadata:
      labels:
        app: teamcloud-jicofo
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      containers:
       - name: jicofo
         image: jitsi/jicofo
#         restartPolicy: Always
         env:
          - name: XMPP_SERVER
            value: prosody.default.svc.cluster.local
          - name: XMPP_DOMAIN
            value: meet.jitsi
          - name: XMPP_AUTH_DOMAIN
            value: auth.meet.jitsi
          - name: JICOFO_COMPONENT_SECRET
            value: s3cr37
          - name: JICOFO_AUTH_USER
            value: focus
          - name: JICOFO_AUTH_PASSWORD
            value: passw0rd
          - name: JVB_BREWERY_MUC
            value: jvbbrewery
          - name: XMPP_INTERNAL_MUC_DOMAIN
            value: internal-muc.meet.jitsi
          - name: TZ
            value: Europe/Paris